# Where a color name is expected, you can use the following hex formats:
# #RGB
# #RRGGBB
# #AARRGGBB (with alpha)
# 'transparent' (no color)
# <color_ref> (e.g 'colors.accents.red'): references this theme's definition if available, the parent's otherwise
#
# Where a color is expected, you can either use a simple string for the color name or the following table syntax:
# [colors.core]
# accent = "accents.color.red"
# OR:
# accent = { name = "accents.color.red", opacity = 0.5 }
# OR:
# accent = { name = "accents.color.red", lighter = 100 }
# OR:
# accent = { name = "accents.color.red", darker = 150 }

[meta]
name = "Tokyonight Night"
description = "Tokyonight theme inspired by tokyonight.nvim"
variant = "dark"
inherit = "tokyo-night"
icon = "icons/theme-name.png"

[colors.core]
accent = "#283457"
accent_foreground = "#c0caf5"
background = "#111118"
foreground = "#a9b1d6"
secondary_background = "#1a1b26"
border = "#232533"

[colors.accents]
blue = "#7aa2f7"
green = "#9ece6a"
magenta = "#9d7cd8"
orange = "#ff9e64"
red = "#f7768e"
yellow = "#bfae78"
cyan = "#1abc9c"
purple = "#bb9af7"

[colors.list.item.selection]
background = "colors.core.accent"

[colors.grid.item]
hover = { outline = "colors.core.foreground" }
selection = { outline = "colors.core.foreground" }

[colors.button.primary]
background = "#292e42"
hover = { background = { name = "colors.core.secondary_background", lighter = 125 } }
focus = { outline = "colors.accents.blue" }
